Repository irisnet/irismod, pull requests merged in 2021-05, with the labels that each got.

#175 Update protobuf
  modules/coinswap/types/coinswap.pb.go
  modules/coinswap/types/genesis.pb.go
  modules/coinswap/types/query.pb.go
  modules/coinswap/types/tx.pb.go
  modules/htlc/types/genesis.pb.go
  modules/htlc/types/htlc.pb.go
  modules/htlc/types/query.pb.go
  modules/htlc/types/tx.pb.go
  modules/nft/types/genesis.pb.go
  modules/nft/types/nft.pb.go
  modules/nft/types/query.pb.go
  modules/nft/types/tx.pb.go
  modules/oracle/types/genesis.pb.go
  modules/oracle/types/oracle.pb.go
  modules/oracle/types/query.pb.go
  modules/oracle/types/tx.pb.go
  modules/random/types/genesis.pb.go
  modules/random/types/query.pb.go
  modules/random/types/random.pb.go
  modules/random/types/tx.pb.go
  modules/record/types/genesis.pb.go
  modules/record/types/query.pb.go
  modules/record/types/record.pb.go
  modules/record/types/tx.pb.go
  modules/service/types/genesis.pb.go
  modules/service/types/query.pb.go
  modules/service/types/service.pb.go
  modules/service/types/tx.pb.go
  modules/token/types/genesis.pb.go
  modules/token/types/query.pb.go
  modules/token/types/token.pb.go
  modules/token/types/tx.pb.go
Labels: automerge

#174 Add farm module
  go.sum
  modules/coinswap/keeper/keeper.go
  modules/farm/abci.go
  modules/farm/client/cli/cli_test.go
  modules/farm/client/cli/flags.go
  modules/farm/client/cli/query.go
  modules/farm/client/cli/tx.go
  modules/farm/client/rest/rest.go
  modules/farm/client/rest/tx.go
  modules/farm/genesis.go
  modules/farm/handler.go
  modules/farm/keeper/farm_info.go
  modules/farm/keeper/grpc_query.go
  modules/farm/keeper/invariants.go
  modules/farm/keeper/keeper.go
  modules/farm/keeper/keeper_test.go
  modules/farm/keeper/msg_server.go
  modules/farm/keeper/params.go
  modules/farm/keeper/pool.go
  modules/farm/keeper/queue.go
  modules/farm/module.go
  modules/farm/simulation/decoder.go
  modules/farm/simulation/genesis.go
  modules/farm/simulation/operations.go
  modules/farm/types/codec.go
  modules/farm/types/errors.go
  modules/farm/types/event.go
  modules/farm/types/expected_keeper.go
  modules/farm/types/farm.go
  modules/farm/types/farm.pb.go
  modules/farm/types/farm_test.go
  modules/farm/types/genesis.go
  modules/farm/types/genesis.pb.go
  modules/farm/types/keys.go
  modules/farm/types/msgs.go
  modules/farm/types/params.go
  modules/farm/types/query.pb.go
  modules/farm/types/query.pb.gw.go
  modules/farm/types/tx.pb.go
  modules/farm/types/validation.go
  modules/farm/types/validation_test.go
  proto/farm/farm.proto
  proto/farm/genesis.proto
  proto/farm/query.proto
  proto/farm/tx.proto
  simapp/app.go
Labels: farm

#176 update coinswap-simulation
  modules/coinswap/simulation/operations.go
Labels: automerge, test
