Repository irisnet/irismod, pull requests merged in 2021-01, with the labels that each got.

#68 Remove standard denom from params and replace prefix ”uni:“ with ”swap/“
  Makefile
  modules/coinswap/client/rest/grpc_query_test.go
  modules/coinswap/client/rest/query.go
  modules/coinswap/client/rest/rest.go
  modules/coinswap/client/rest/tx.go
  modules/coinswap/genesis.go
  modules/coinswap/keeper/grpc_query.go
  modules/coinswap/keeper/keeper.go
  modules/coinswap/keeper/keeper_test.go
  modules/coinswap/keeper/querier.go
  modules/coinswap/keeper/swap.go
  modules/coinswap/types/coinswap.pb.go
  modules/coinswap/types/genesis.go
  modules/coinswap/types/genesis.pb.go
  modules/coinswap/types/msgs.go
  modules/coinswap/types/params.go
  modules/coinswap/types/querier.go
  modules/coinswap/types/query.pb.go
  modules/coinswap/types/query.pb.gw.go
  proto/coinswap/coinswap.proto
  proto/coinswap/genesis.proto
  proto/coinswap/query.proto
Labels: bug, enhancement

#70 Fix minimum deposit calculation
  modules/service/keeper/binding.go
  modules/service/keeper/invocation.go
  modules/service/keeper/keeper_test.go
  modules/service/keeper/module_service.go
  modules/service/keeper/oracle_price.go
  modules/service/types/errors.go
  modules/service/types/invocation.go
  modules/service/types/msgs.go
  modules/service/types/msgs_test.go
  modules/service/types/oracle_price.go
  modules/service/types/schema.go
  modules/service/types/token.go
  modules/token/types/msgs.go
  modules/token/types/token.go
Labels: bug

#81 Fix genesis export and import
  modules/htlc/genesis.go
  modules/htlc/types/genesis.go
  modules/htlc/types/htlc.go
  modules/htlc/types/msgs.go
  modules/service/genesis.go
  modules/service/types/genesis.go
  modules/service/types/genesis.pb.go
  proto/service/genesis.proto
Labels: bug, enhancement

#84 Normalize msg and refactor validation logic
  modules/coinswap/handler.go
  modules/coinswap/types/errors.go
  modules/coinswap/types/genesis.go
  modules/coinswap/types/msgs.go
  modules/coinswap/types/msgs_test.go
  modules/coinswap/types/utils.go
  modules/coinswap/types/validation.go
  modules/htlc/handler.go
  modules/htlc/types/genesis.go
  modules/htlc/types/htlc.go
  modules/htlc/types/msgs.go
  modules/htlc/types/validation.go
  modules/nft/handler.go
  modules/nft/keeper/denom.go
  modules/nft/keeper/keeper.go
  modules/nft/keeper/msg_server.go
  modules/nft/keeper/owners.go
  modules/nft/types/denom.go
  modules/nft/types/keys.go
  modules/nft/types/msgs.go
  modules/nft/types/msgs_test.go
  modules/nft/types/nft.go
  modules/nft/types/validation.go
  modules/oracle/handler.go
  modules/oracle/keeper/keeper.go
  modules/oracle/types/genesis.go
  modules/oracle/types/msgs.go
  modules/oracle/types/msgs_test.go
  modules/oracle/types/validation.go
  modules/random/handler.go
  modules/random/types/errors.go
  modules/random/types/msgs.go
  modules/random/types/validation.go
  modules/record/genesis.go
  modules/record/handler.go
  modules/record/types/msgs.go
  modules/record/types/validation.go
  modules/service/handler.go
  modules/service/types/msgs.go
  modules/service/types/validation.go
  modules/token/client/cli/cli_test.go
  modules/token/client/cli/query.go
  modules/token/client/rest/grpc_query_test.go
  modules/token/client/rest/query.go
  modules/token/handler.go
  modules/token/keeper/grpc_query.go
  modules/token/keeper/querier.go
  modules/token/types/msgs.go
  modules/token/types/token.go
  modules/token/types/token_test.go
  modules/token/types/validation.go
Labels: enhancement

#82 Do not use msg as the keeper functions input parameter
  modules/token/handler_test.go
  modules/token/keeper/keeper.go
  modules/token/keeper/keeper_test.go
  modules/token/keeper/msg_server.go
  modules/token/keeper/token.go
  modules/token/types/errors.go
Labels: modules/token

#91 Improve token validation
  modules/token/genesis.go
  modules/token/types/validation.go
Labels: enhancement, modules/token

#89 Remove normalize code
  modules/coinswap/handler.go
  modules/coinswap/types/msgs.go
  modules/coinswap/types/params.go
  modules/htlc/handler.go
  modules/htlc/types/msgs.go
  modules/nft/client/cli/query.go
  modules/nft/client/rest/query.go
  modules/nft/genesis.go
  modules/nft/handler.go
  modules/nft/keeper/grpc_query.go
  modules/nft/keeper/querier.go
  modules/nft/module.go
  modules/nft/types/genesis.go
  modules/nft/types/msgs.go
  modules/nft/types/msgs_test.go
  modules/nft/types/owners.go
  modules/nft/types/validation.go
  modules/oracle/handler.go
  modules/oracle/keeper/grpc_query.go
  modules/oracle/keeper/keeper.go
  modules/oracle/keeper/querier.go
  modules/oracle/types/msgs.go
  modules/oracle/types/msgs_test.go
  modules/oracle/types/validation.go
  modules/random/handler.go
  modules/random/types/msgs.go
  modules/record/genesis.go
  modules/record/handler.go
  modules/record/module.go
  modules/record/types/genesis.go
  modules/record/types/msgs.go
  modules/service/exported/exported.go
  modules/service/handler.go
  modules/service/keeper/grpc_query.go
  modules/service/keeper/querier.go
  modules/service/types/msgs.go
  modules/service/types/validation.go
  modules/service/types/validation_test.go
  modules/token/client/cli/cli_test.go
  modules/token/client/cli/tx.go
  modules/token/client/rest/grpc_query_test.go
  modules/token/client/rest/tx.go
  modules/token/genesis.go
  modules/token/handler.go
  modules/token/keeper/querier.go
  modules/token/module.go
  modules/token/types/genesis.go
  modules/token/types/msgs.go
  modules/token/types/msgs_test.go
Labels: enhancement

#93 Update changelog
  CHANGELOG.md
Labels: documentation

#96 Modify service event name
  modules/service/types/events.go
Labels: modules/service

#98 Release v1.2.1
  CHANGELOG.md
Labels: documentation
