Repository irisnet/irismod, pull requests merged in 2021-02, with the labels that each got.

#101 Mint&Edit&Burn only accept symbol as denom
  modules/token/keeper/keeper.go
  modules/token/keeper/msg_server.go
  modules/token/keeper/token.go
Labels: bug

#97 "TotalBurn" method remove unit convert
  modules/token/keeper/grpc_query.go
  modules/token/keeper/grpc_query_test.go
  modules/token/types/query.pb.go
  proto/token/query.proto
Labels: enhancement, modules/token

#105 Add service tax account
  modules/nft/types/validation.go
  modules/service/client/cli/cli_test.go
  modules/service/keeper/fees.go
  modules/service/keeper/keeper.go
  modules/service/types/keys.go
  simapp/app.go
Labels: enhancement, modules/service

#108 Adjust the number of `issueTokenBaseFee` to keep it with the unit
  modules/token/genesis.go
  modules/token/keeper/fees.go
  modules/token/keeper/keeper.go
  modules/token/keeper/token.go
  modules/token/simulation/operations.go
  modules/token/types/msgs.go
  modules/token/types/msgs_test.go
  modules/token/types/params.go
  modules/token/types/validation.go
Labels: enhancement, modules/token

#109 Adjust oracle FeedName&ValueJsonPath validation
  modules/oracle/types/genesis.go
  modules/oracle/types/msgs.go
  modules/oracle/types/msgs_test.go
  modules/oracle/types/validation.go
  modules/oracle/types/validation_test.go
Labels: enhancement, modules/oracle

#111 Upgrade cosmos-sdk to v0.41.0
  go.mod
  go.sum
Labels: dependencies

#112 Add unreleased changelog
  CHANGELOG.md
Labels: documentation

#113 Calculate mint token fee error
  modules/token/keeper/fees.go
Labels: bug, modules/token

#114 Modify htlc code commands
  modules/htlc/types/query.pb.go
  proto/htlc/query.proto
Labels: modules/htlc

#115 Normalize keys
  modules/nft/types/validation.go
  modules/oracle/types/keys.go
  modules/random/client/cli/flags.go
  modules/random/keeper/keeper.go
  modules/random/simulation/decoder.go
  modules/random/simulation/decoder_test.go
  modules/random/types/keys.go
  modules/service/keeper/binding.go
  modules/service/types/keys.go
  modules/token/types/keys.go
Labels: enhancement

#117 Add ante for service
  modules/service/keeper/ante.go
  modules/service/types/expected_keeper.go
Labels: enhancement, modules/service

#118 Remove super mode from service
  modules/oracle/keeper/keeper.go
  modules/oracle/keeper/keeper_test.go
  modules/oracle/types/expected_keepers.go
  modules/random/keeper/service.go
  modules/random/types/expected_keepers.go
  modules/service/abci.go
  modules/service/client/cli/flags.go
  modules/service/client/cli/tx.go
  modules/service/client/rest/tx.go
  modules/service/client/utils/query.go
  modules/service/keeper/ante.go
  modules/service/keeper/invocation.go
  modules/service/keeper/keeper_test.go
  modules/service/keeper/msg_server.go
  modules/service/spec/02_messages.md
  modules/service/types/expected_keeper.go
  modules/service/types/genesis.pb.go
  modules/service/types/invocation.go
  modules/service/types/msgs.go
  modules/service/types/msgs_test.go
  modules/service/types/query.pb.go
  modules/service/types/service.pb.go
  modules/service/types/tx.pb.go
  proto/service/service.proto
  proto/service/tx.proto
Labels: bug, enhancement, modules/service

#119 fix oracle cli
  modules/oracle/client/cli/tx.go
Labels: bug, modules/oracle

#122 Optimize module logging
  modules/oracle/keeper/keeper.go
  modules/random/abci.go
Labels: enhancement

#125 Denom name can not space
  modules/nft/keeper/denom.go
  modules/nft/types/errors.go
  modules/nft/types/keys.go
  modules/nft/types/msgs.go
  modules/nft/types/validation.go
Labels: enhancement, modules/nft

#123 Fix the store key for owner service fees
  modules/service/types/keys.go
Labels: bug

#128 Add more tests for service fees
  modules/service/keeper/keeper_test.go
Labels: modules/service, test

#129 Fix token issue fee and cleanup
  modules/nft/types/validation.go
  modules/oracle/client/cli/tx.go
  modules/oracle/types/validation.go
  modules/service/keeper/keeper_test.go
  modules/token/keeper/fees.go
Labels: bug, modules/token

#124 Add v1.3.0 changelog
  CHANGELOG.md
  modules/service/types/validation.go
Labels: release

#131 Clean up
  modules/coinswap/keeper/grpc_query.go
  modules/coinswap/keeper/keeper.go
  modules/coinswap/keeper/keeper_test.go
  modules/coinswap/keeper/swap.go
  modules/coinswap/types/expected_keepers.go
  modules/coinswap/types/genesis.go
  modules/coinswap/types/msgs.go
  modules/coinswap/types/params.go
  modules/coinswap/types/querier.go
  modules/coinswap/types/utils.go
  modules/coinswap/types/validation.go
  modules/htlc/types/expected_keepers.go
  modules/htlc/types/validation.go
  modules/nft/client/cli/flags.go
  modules/nft/client/cli/query.go
  modules/nft/client/cli/tx.go
  modules/nft/client/rest/query.go
  modules/nft/client/rest/rest.go
  modules/nft/client/rest/tx.go
  modules/nft/genesis.go
  modules/nft/keeper/collection.go
  modules/nft/keeper/denom.go
  modules/nft/keeper/invariants.go
  modules/nft/keeper/keeper.go
  modules/nft/keeper/nft.go
  modules/nft/keeper/owners.go
  modules/oracle/client/cli/flags.go
  modules/oracle/client/cli/query.go
  modules/oracle/client/cli/tx.go
  modules/oracle/keeper/feed.go
  modules/oracle/keeper/grpc_query.go
  modules/oracle/keeper/keeper.go
  modules/oracle/types/events.go
  modules/oracle/types/expected_keepers.go
  modules/oracle/types/genesis.go
  modules/oracle/types/validation.go
Labels: enhancement

#135 Cleanup proto
  modules/coinswap/types/coinswap.pb.go
  modules/coinswap/types/genesis.pb.go
  modules/coinswap/types/query.pb.go
  modules/coinswap/types/tx.pb.go
  modules/htlc/types/genesis.pb.go
  modules/htlc/types/htlc.pb.go
  modules/htlc/types/tx.pb.go
  modules/nft/types/genesis.pb.go
  modules/nft/types/nft.pb.go
  modules/oracle/types/genesis.pb.go
  modules/oracle/types/query.pb.go
  modules/oracle/types/tx.pb.go
  modules/random/types/genesis.pb.go
  modules/random/types/tx.pb.go
  modules/record/types/genesis.pb.go
  modules/record/types/record.pb.go
  modules/record/types/tx.pb.go
  modules/service/types/genesis.pb.go
  modules/service/types/query.pb.go
  modules/service/types/service.pb.go
  modules/service/types/tx.pb.go
  modules/token/types/genesis.pb.go
  modules/token/types/query.pb.go
  modules/token/types/token.pb.go
  modules/token/types/tx.pb.go
  proto/coinswap/coinswap.proto
  proto/coinswap/genesis.proto
  proto/coinswap/query.proto
  proto/coinswap/tx.proto
  proto/htlc/genesis.proto
  proto/htlc/htlc.proto
  proto/htlc/query.proto
  proto/htlc/tx.proto
  proto/nft/genesis.proto
  proto/nft/nft.proto
  proto/nft/query.proto
  proto/oracle/genesis.proto
  proto/oracle/query.proto
  proto/oracle/tx.proto
  proto/random/genesis.proto
  proto/random/tx.proto
  proto/record/genesis.proto
  proto/record/query.proto
  proto/record/record.proto
  proto/record/tx.proto
  proto/service/genesis.proto
  proto/service/query.proto
  proto/service/service.proto
  proto/service/tx.proto
  proto/token/genesis.proto
  proto/token/query.proto
  proto/token/token.proto
  proto/token/tx.proto
Labels: enhancement

#132 Clean up
  modules/random/client/cli/flags.go
  modules/random/genesis.go
  modules/random/keeper/keeper.go
  modules/random/keeper/service.go
  modules/random/types/genesis.go
  modules/random/types/keys.go
  modules/random/types/msgs.go
  modules/random/types/random.go
  modules/random/types/request.go
  modules/random/types/rng.go
  modules/random/types/validation.go
  modules/record/client/cli/flags.go
  modules/record/genesis.go
  modules/record/keeper/keeper.go
  modules/record/types/expected_keepers.go
  modules/record/types/genesis.go
  modules/record/types/keys.go
  modules/record/types/msgs.go
  modules/record/types/querier.go
  modules/record/types/types.go
  modules/record/types/validation.go
  modules/service/client/cli/flags.go
  modules/service/exported/exported.go
  modules/service/genesis.go
  modules/service/keeper/binding.go
  modules/service/keeper/keeper.go
  modules/service/types/errors.go
  modules/service/types/expected_keeper.go
  modules/service/types/genesis.go
  modules/service/types/utils.go
  modules/service/types/validation.go
  modules/token/client/cli/flags.go
  modules/token/client/cli/query.go
  modules/token/client/cli/tx.go
  modules/token/client/rest/query.go
  modules/token/genesis.go
  modules/token/handler.go
  modules/token/keeper/fees.go
  modules/token/keeper/keeper.go
  modules/token/keeper/token.go
  modules/token/types/errors.go
  modules/token/types/expected_keepers.go
  modules/token/types/genesis.go
  modules/token/types/keys.go
  modules/token/types/params.go
  modules/token/types/token.go
  modules/token/types/validation.go
Labels: enhancement

#130 Update oracle default flag value
  modules/oracle/client/cli/flags.go
Labels: enhancement

#126 Update irismod token spec
  modules/token/spec/01_state.md
  modules/token/spec/02_messages.md
  modules/token/spec/03_events.md
  modules/token/spec/03_params.md
  modules/token/spec/04_params.md
  modules/token/spec/README.md
Labels: documentation

#127 Update irismod record spec
  modules/record/spec/01_state.md
  modules/record/spec/02_messages.md
  modules/record/spec/03_events.md
  modules/record/spec/README.md
Labels: documentation

#133 Update irismod service spec
  modules/service/spec/01_state.md
  modules/service/spec/02_messages.md
  modules/service/spec/03_events.md
  modules/service/spec/04_params.md
  modules/service/spec/README.md
Labels: documentation

#137 Remove the unnecessary delimiter in service key
  modules/service/keeper/keeper_test.go
  modules/service/types/keys.go
Labels: enhancement

#138 Modify price regex in the service pricing schema
  modules/service/keeper/keeper_test.go
  modules/service/types/msgs_test.go
  modules/service/types/schema.go
Labels: bug

#139 Release v1.3.1
  CHANGELOG.md
  modules/token/keeper/token.go
Labels: release

#141 Add automerge workflows
  .github/workflows/automerge.yml
Labels: automerge

#87 Improve service
  modules/service/client/cli/cli_test.go
  modules/service/keeper/binding.go
  modules/service/keeper/fees.go
  modules/service/keeper/invocation.go
  modules/service/keeper/keeper.go
  modules/service/keeper/keeper_test.go
  modules/service/keeper/params.go
  modules/service/spec/01_state.md
  modules/service/spec/04_params.md
  modules/service/types/binding.go
  modules/service/types/keys.go
  modules/service/types/msgs.go
  modules/service/types/params.go
  modules/service/types/service.pb.go
  modules/service/types/validation.go
  proto/service/service.proto
  simapp/app.go
Labels: automerge, modules/service
